=== Nostalgica-Reverie/Content-Monorepo/docs/packwand/spec/schemas/mod.json
{
	"type": "object",
	"$schema": "http://json-schema.org/draft-07/schema",
	"title": "mod.pw.toml",
	"description": "A metadata file which references an external file from a URL (or a metadata-based downloader). This allows for side-only mods, optional mods and pinning, and stores metadata to allow finding updates from Modrinth, CurseForge, GitHub, GitLab, and Forgejo. The \"mod\" terminology is used a lot here, but this should work for any file.",
	"examples": [
		"name = \"Borderless Mining\"\nfilename = \"borderless-mining-1.1.5+1.19.jar\"\nside = \"client\"\n\n[download]\nurl = \"https://cdn.modrinth.com/data/kYq5qkSL/versions/1.1.5+1.19/borderless-mining-1.1.5%2B1.19.jar\"\nhash-format = \"sha1\"\nhash = \"08f98e28057a0fbdb288c947b7871def4b18b176\"\n\n[update]\n[update.modrinth]\nmod-id = \"kYq5qkSL\"\nversion = \"gqoXgtxO\"\n"
	],
	"properties": {
		"name": {
			"description": "The name of the mod, which can be displayed in user interfaces to identify the mod. It does not need to be unique between mods, although this may cause confusion.",
			"examples": ["Borderless Mining"],
			"type": "string"
		},
		"filename": {
			"type": "string",
			"description": "The destination path of the mod file, relative to this file.\n\nA relative path using forward slashes. Must not reference a file outside the pack root, and should not include characters or filenames restricted on common operating systems.\n\nImplementations must support special characters including those that are percent-encoded in URLs, such as spaces and square brackets. Implementations must guard against path traversal attacks and manually validate paths.",
			"pattern": "^([^/\\x00-\\x1F\\x7F\"*/:<>?\\\\|]+\\/)*[^/\\x00-\\x1F\\x7F\"*/:<>?\\\\|]*$",
			"examples": ["borderless-mining-1.1.5+1.19.jar"]
		},
		"side": {
			"description": "The side on which this mod should be installed.\n\nA physical Minecraft side. Server applies to the dedicated server, client applies to the client (and integrated server), and both applies to every installation.",
			"enum": ["both", "client", "server"],
			"default": "both",
			"type": "string"
		},
		"pin": {
			"description": "packwand extension: when true, the file is pinned and update commands skip it until it is unpinned (packwand pin / packwand unpin).",
			"default": false,
			"type": "boolean"
		},
		"download": {
			"type": "object",
			"description": "Information about how to download this mod.",
			"properties": {
				"url": {
					"type": "string",
					"description": "The URL to download the mod from. Required when mode is \"url\" or omitted; not present in metadata download modes.\n\nAn absolute URI compliant with RFC 3986. Implementations may need to be more lenient in accepting reserved characters in paths due to historical implementation bugs. Only the HTTP/HTTPS protocols must be supported, other protocols should not be used.",
					"format": "uri"
				},
				"mode": {
					"description": "The download mode. \"url\" (or omitted/empty) downloads from the url field. \"metadata:curseforge\" resolves the download URL through the CurseForge API using the [update.curseforge] metadata, as required by CurseForge's distribution rules; such files have no url field.",
					"enum": ["url", "metadata:curseforge"],
					"default": "url",
					"type": "string"
				},
				"hash": {
					"type": "string",
					"description": "The hash of the specified file, as a string.\n\nBinary hashes should be stored as hexadecimal, and case should be ignored during parsing. Numeric hashes (e.g. Murmur2) should still be stored as a string, to ensure the value is preserved correctly.",
					"examples": ["08f98e28057a0fbdb288c947b7871def4b18b176"]
				},
				"hash-format": {
					"type": "string",
					"description": "The hash format for the hash of the specified file.\n\nThe hash algorithm used to determine if a file is valid. All functions listed must be supported by tools implementing the packwand pack format.",
					"enum": ["sha256", "sha512", "sha1", "md5", "murmur2"],
					"x-taplo": {
						"docs": {
							"enumValues": [
								"The SHA2-256 hashing standard. Used as the download-cache key format.",
								"The SHA2-512 hashing standard. Used by default for all new files and index entries.",
								"The SHA1 hashing standard.",
								"The MD5 hashing standard.",
								"The CurseForge variant of MurmurHash2: MurmurHash2 32-bit hashing standard (seed 1) with some characters removed before applying the hash (decimal bytes 9, 10, 13, 32), stored as an unsigned integer.\n\nIn Java, use Integer.parseUnsignedInt to parse this value."
							]
						}
					}
				}
			},
			"required": ["hash", "hash-format"]
		},
		"option": {
			"type": "object",
			"description": "Information about the optional state of this mod. When excluded, this indicates that the mod is not optional.",
			"properties": {
				"optional": {
					"description": "Whether or not the mod is optional. This can be set to false if you want to keep the description but make the mod required.",
					"default": false,
					"type": "boolean"
				},
				"description": {
					"description": "A description displayed to the user when they select optional mods. This should explain why or why not the user should enable the mod.",
					"type": "string"
				},
				"default": {
					"description": "If true, the mod will be enabled by default. If false, the mod will be disabled by default. If a pack format does not support optional mods but it does support disabling mods, the mod will be disabled if it defaults to being disabled.",
					"default": false,
					"type": "boolean"
				}
			},
			"required": ["optional"]
		},
		"update": {
			"type": "object",
			"description": "Information about how to update the download details of this mod with tools.\n\nIf this object does not exist or there are no defined update sources, the mod will not be automatically updated.\n\nIf there are multiple defined update sources, one of them will be chosen. The source that is chosen is not defined, so it is therefore dependent on the implementation of the tool (may not be deterministic, so do not rely on one source being chosen over another).",
			"additionalProperties": {
				"type": "object",
				"description": "Implementations are free to support other update sources, but it would be beneficial to document and standardise these."
			},
			"properties": {
				"curseforge": {
					"type": "object",
					"description": "An update source for updating mods downloaded from CurseForge.",
					"properties": {
						"project-id": {
							"description": "An integer representing the unique project ID of this mod. Updating will retrieve the latest file for this project ID that is valid (correct Minecraft version, release channel, modloader, etc.).",
							"examples": [327154],
							"type": "number"
						},
						"file-id": {
							"description": "An integer representing the unique file ID of this mod file. This can be used if more metadata needs to be obtained relating to the mod.",
							"examples": [3643025],
							"type": "number"
						}
					},
					"required": ["project-id", "file-id"]
				},
				"modrinth": {
					"type": "object",
					"description": "An update source for updating mods downloaded from Modrinth.",
					"properties": {
						"mod-id": {
							"description": "A string representing the unique mod ID of this mod. Updating will retrieve the latest file for this project ID that is valid (correct Minecraft version, release channel, modloader, etc.).",
							"examples": ["kYq5qkSL"],
							"type": "string"
						},
						"version": {
							"description": "A string representing the unique version ID of this file. This can be used if more metadata needs to be obtained relating to the mod.",
							"examples": ["gqoXgtxO"],
							"type": "string"
						}
					},
					"required": ["mod-id", "version"]
				},
				"github": {
					"type": "object",
					"description": "packwand extension: an update source for updating mods downloaded from GitHub release assets.",
					"properties": {
						"slug": {
							"description": "The repository, as owner/repo.",
							"examples": ["CaffeineMC/sodium"],
							"type": "string"
						},
						"tag": {
							"description": "The currently-installed release tag.",
							"type": "string"
						},
						"branch": {
							"description": "Restrict updates to releases targeting this branch.",
							"type": "string"
						},
						"regex": {
							"description": "A regular expression an asset filename must match to be selected.",
							"type": "string"
						}
					},
					"required": ["slug"]
				},
				"gitlab": {
					"type": "object",
					"description": "packwand extension: an update source for updating mods downloaded from GitLab release assets.",
					"properties": {
						"instance": {
							"description": "The GitLab instance hostname. Defaults to gitlab.com.",
							"default": "gitlab.com",
							"type": "string"
						},
						"slug": {
							"description": "The project path, as owner/repo.",
							"type": "string"
						},
						"tag": {
							"description": "The currently-installed release tag.",
							"type": "string"
						},
						"regex": {
							"description": "A regular expression an asset filename must match to be selected.",
							"type": "string"
						}
					},
					"required": ["slug"]
				},
				"forgejo": {
					"type": "object",
					"description": "packwand extension: an update source for updating mods downloaded from Forgejo/Gitea release assets (including Codeberg).",
					"properties": {
						"instance": {
							"description": "The Forgejo/Gitea instance hostname. Defaults to codeberg.org.",
							"default": "codeberg.org",
							"type": "string"
						},
						"slug": {
							"description": "The repository, as owner/repo.",
							"type": "string"
						},
						"tag": {
							"description": "The currently-installed release tag.",
							"type": "string"
						},
						"branch": {
							"description": "Restrict updates to releases targeting this branch.",
							"type": "string"
						},
						"regex": {
							"description": "A regular expression an asset filename must match to be selected.",
							"type": "string"
						}
					},
					"required": ["slug"]
				}
			},
			"required": []
		}
	},
	"required": ["name", "filename", "download"]
}

=== Nostalgica-Reverie/Content-Monorepo/modpacks/vital/26.2-mr/mods/lambdynamiclights.pw.json
{
  "name": "LambDynamicLights",
  "filename": "lambdynamiclights-4.12.2+26.2.jar",
  "side": "client",
  "download": {
    "url": "https://cdn.modrinth.com/data/yBW8D80W/versions/jBLH7Qy8/lambdynamiclights-4.12.2%2B26.2.jar",
    "hash-format": "sha512",
    "hash": "3c2ab4028e47da4155e860c9449231d7b17e10dc6d9d110ab58dc621ab806fcc0b21741c73a671c0d72fb9ae5021792cea18f09b515180ae33e86c4008c3d139"
  },
  "update": {
    "modrinth": {
      "mod-id": "yBW8D80W",
      "version": "jBLH7Qy8"
    }
  }
}

=== Nostalgica-Reverie/Content-Monorepo/modpacks/reminiscence/1.20.1-mr/mods/puffish_attributes-0.8.1-1.20-forge.pw.json
{
  "name": "puffish_attributes-0.8.1-1.20-forge",
  "filename": "puffish_attributes-0.8.2-1.20-forge.jar",
  "side": "both",
  "download": {
    "url": "https://cdn.modrinth.com/data/FCFcFw09/versions/IG5KY4Qf/puffish_attributes-0.8.2-1.20-forge.jar",
    "hash-format": "sha512",
    "hash": "b8d2829d665d29dc6e6b48b6e8973d3002c07d5a0ddc3dc46d052abcc13d3a06eaa3b7669464db902b5642f2f9d923f3612c8a84317f0e567515f59c133d572b"
  },
  "update": {
    "modrinth": {
      "mod-id": "FCFcFw09",
      "version": "IG5KY4Qf"
    }
  }
}

=== Nostalgica-Reverie/Content-Monorepo/modpacks/legacy4server/26.1.2-mr/mods/structure-layout-optimizer.pw.json
{
  "name": "Structure Layout Optimizer",
  "filename": "structure_layout_optimizer-1.1.4+26.1-fabric.jar",
  "side": "server",
  "download": {
    "url": "https://cdn.modrinth.com/data/ayPU0OHc/versions/JwbecFqq/structure_layout_optimizer-1.1.4%2B26.1-fabric.jar",
    "hash-format": "sha512",
    "hash": "d0a443e5a71dc6a40f6345b49b73aee5290d5726f68a5b05d3b31b9ff71262dd2986518df8a560f2097e7584b944ff462d621499f5dede10afa624a34359e8cc"
  },
  "update": {
    "modrinth": {
      "mod-id": "ayPU0OHc",
      "version": "JwbecFqq"
    }
  }
}

=== Nostalgica-Reverie/Content-Monorepo/modpacks/reminiscence/1.20.1-cf/mods/hookshot-from-zelda.pw.json
{
  "name": "Hookshot - From Zelda",
  "filename": "hookshot-1.20.1-1.1.3.jar",
  "side": "both",
  "download": {
    "hash-format": "sha1",
    "hash": "ff724ed618ce6e554ed97101184efc06aea5754a",
    "mode": "metadata:curseforge"
  },
  "update": {
    "curseforge": {
      "file-id": 8447042,
      "project-id": 1065199,
      "release-channel": ""
    }
  }
}

=== Nostalgica-Reverie/Content-Monorepo/modpacks/re-console-main/26.1.2-mr/mods/fabric-language-kotlin.bun.json
{
  "name": "Fabric Language Kotlin",
  "filename": "fabric-language-kotlin-1.13.13+kotlin.2.4.10.jar",
  "side": "both",
  "download": {
    "url": "https://cdn.modrinth.com/data/Ha28R6CL/versions/bdhiINYC/fabric-language-kotlin-1.13.13%2Bkotlin.2.4.10.jar",
    "hash-format": "sha512",
    "hash": "9a63c35a550b0362b7b25ff045d93709c7b0dae08c89076cba422813fdfb9e5f5dd021ed3afac9f82e74e95b88c249e8f68b240717151540ca3e88cc27fb9c77"
  },
  "update": {
    "modrinth": {
      "mod-id": "Ha28R6CL",
      "version": "bdhiINYC"
    }
  }
}

=== Nostalgica-Reverie/Content-Monorepo/modpacks/reminiscence/1.20.1-mr/mods/crafttweaker.pw.json
{
  "name": "CraftTweaker",
  "filename": "CraftTweaker-forge-1.20.1-14.0.60.jar",
  "side": "both",
  "download": {
    "url": "https://cdn.modrinth.com/data/Xg35A4rS/versions/8GR4gItx/CraftTweaker-forge-1.20.1-14.0.60.jar",
    "hash-format": "sha512",
    "hash": "7352168dffbdc23b472f767940c9c139b321d940b496bf8505c502c35aed33f686d35b2b3b67acbf5a4efb82ad90907412df67a85f6464ea685445d9655e9679"
  },
  "update": {
    "modrinth": {
      "mod-id": "Xg35A4rS",
      "version": "8GR4gItx"
    }
  }
}

=== Nostalgica-Reverie/Content-Monorepo/modpacks/re-console-main/26.1.2-cf/mods/pro-placer.pw.json
{
  "name": "Pro Placer",
  "filename": "ProPlacer-v26.1.0-mc26.1.x-Fabric.jar",
  "side": "both",
  "download": {
    "hash-format": "sha1",
    "hash": "93c81de3deab581c422aa9d86e8f0decc915e32a",
    "mode": "metadata:curseforge"
  },
  "update": {
    "curseforge": {
      "file-id": 7987095,
      "project-id": 368320
    }
  }
}

=== Nostalgica-Reverie/Content-Monorepo/modpacks/rekindled/tu3-mr/mods/particle-core.pw.json
{
  "name": "Particle Core",
  "filename": "particle_core-0.3.3+1.21+neoforge.jar",
  "side": "client",
  "download": {
    "url": "https://cdn.modrinth.com/data/RSeLon5O/versions/2QF4NhZD/particle_core-0.3.3%2B1.21%2Bneoforge.jar",
    "hash-format": "sha512",
    "hash": "bf14200f4f279c2c5f5a50e09ef561f34463848fde507cb5930e4f4dbfed107697387ce030593be37a14da73cc459b0901928466fb44b2c2a387c584f38ec489"
  },
  "update": {
    "modrinth": {
      "mod-id": "RSeLon5O",
      "version": "2QF4NhZD"
    }
  }
}
